### ISSUE TITLE
Conscript installation failing

### ISSUE THREAD

**Issue by FranklinChen** [jove-sh/jove-notebook#1]
I'm getting from

```
$ cs jove-sh/jove-notebook
```

the error

```
module not found: sh.jove#jove-notebook-bootstrap_2.10;0.1.1-SNAPSHOT
```

**Comment by alexarchambault** [comment]
Ok, that again...
I'll update the launchconfig quickly. In the mean time, you can download pre-packaged binaries from 
https://oss.sonatype.org/content/repositories/snapshots/sh/jove/jove-notebook-scala_2.11/0.1.1-1-SNAPSHOT/jove-notebook-scala_2.11-0.1.1-1-SNAPSHOT.tar.gz or
https://oss.sonatype.org/content/repositories/snapshots/sh/jove/jove-notebook-spark_1.2_2.11/0.1.1-1-SNAPSHOT/jove-notebook-spark_1.2_2.11-0.1.1-1-SNAPSHOT.tar.gz

I'll update the README too.

Sorry about all that, thanks for the report!

**Comment by alexarchambault** [comment]
Firstly, I'm deprecating the conscript install. It was way too slow, and cumbersome to maintain and test. Ready-to-run packages are now the recommended way of running jove-notebook (see links in README).

Closing this issue for now, as conscript install is working again although it's now deprecated. Feel free to re-open if you're still running into problems.
